### DISCUSSION TITLE
Beta version of ESP-Modbus stack v2.0.0-beta

### DISCUSSION THREAD

**Discussion by alisitsyn** [espressif/esp-modbus#45] [Announcements]
## Overview

The current release of ESP-Modbus is beta, corresponds to the version `v2.0.0-beta.1` and supports creation of several instances of modbus master and slave objects. The public API interface is changed to allow creation of multiple communication objects with its own communication parameters, and the constructor API upon creation returns the handle to the interface structure that must be used as a first parameter for each API call for this particular object. For more information about the interface API and related changes see the official documentation for this release, described below. The goal of this beta release is to introduce new features and changes to the end users and get their feedback. The appropriate information or feature requests can be shared over on discussion page of the project.

- [Release branch v2.0.0-beta.1](https://github.com/espressif/esp-modbus/tree/release/v2.0)

* [Discussions](https://github.com/espressif/esp-modbus/discussions/categories/general)
* [Issues](https://github.com/espressif/esp-modbus/labels/v2.0.0-beta)
* The pre-release esp-modbus component version: [2.0.0-beta.1](https://components.espressif.com/components/espressif/esp-modbus/versions/2.0.0-beta.1)

## Documentation

The documentation can be found on the link below:

* [ESP-Modbus documentation (English)](https://docs.espressif.com/projects/esp-modbus/en/v2.0.0-beta/esp32/index.html)

## Application Examples

The examples below demonstrate the ESP-Modbus library of serial, TCP ports for slave and master implementations accordingly.

- [Modbus serial slave example](https://github.com/espressif/esp-modbus/tree/release/v2.0/examples/serial/mb_serial_slave)

- [Modbus serial master example](https://github.com/espressif/esp-modbus/tree/release/v2.0/examples/serial/mb_serial_master)

- [Modbus TCP master example](https://github.com/espressif/esp-modbus/tree/release/v2.0/examples/tcp/mb_tcp_master)

- [Modbus TCP slave example](https://github.com/espressif/esp-modbus/tree/release/v2.0/examples/tcp/mb_tcp_slave)

## Included Features And Changes

 * The stack supports creation of multiple instances of master and slave with individual communication options and extended list of parameters;
 * Master uses new extended format of slave connection table with the format: `UID;IP address or host name;PORT;`
  Examples:  `12:2001:0db8:85a3:0000:0000:8a2e:0370:7334:502` - Defines the slave with defined IPV6, UID=12, PORT = 502,
  `01:mb_slave_tcp_01:1502` - The slave with host name `mb_slave_tcp_01`, with UID=01 and PORT = 1502.
 * The Modbus Master TCP controls the states of each slave individually and is able to renew connection/resolving phase if the slave connection is lost while it keeps polling cycle to remaining slaves.
 * The Master is able to send request to the slave with any UID using specific API functions following with prefix `_with`;
 * Support of Modbus TCP Master and Modbus TCP Slave multi-instance  communication through the common driver;
 * The pre-release esp-modbus component version [2.0.0-beta.1](https://components.espressif.com/components/espressif/esp-modbus/versions/2.0.0-beta.1) can be selected for your project using the manifest file in main folder like below:
 `idf_component.yml`:
    ``` yml
    dependencies:
      idf:
         version: ">=4.1.0"
      espressif/esp-modbus:
        version: "^2.0.0-beta" # this line selects the v2.0.0-beta component release
      espressif/mdns:
        version: "^1.0.0"
        rules:
          - if: "idf_version >=5.0"
      mb_example_common:
        path: "../mb_example_common"
      protocol_examples_common:
        path: ${IDF_PATH}/examples/common_components/protocol_examples_common
    ```

## Related Issues

 * [How to Read Device Identification Function 43 / 14 (0x2B / 0x0E) with MODBUS Master RTU (IDFGH-9653)](https://github.com/espressif/esp-modbus/issues/24) (Status: postponed)
 * [How to organize polling of a large number of IP addresses via Modbus TCP (for example, 30)? (IDFGH-9251)](https://github.com/espressif/esp-modbus/issues/19) (Status: released)
 * [port0 and port1 work with modbus RTU two instance of a slave at the same time (IDFGH-7798)](https://github.com/espressif/esp-modbus/issues/9) (Status: released)
 * [run both tcp and rtu slave at same time (IDFGH-7663)](https://github.com/espressif/esp-modbus/issues/8) (Status: released)
 * [2 vs 4 byte IEEE754 floats in power meters (IDFGH-7198)](https://github.com/espressif/esp-modbus/issues/3) (Status: released)
 * [How to add word_length & stop_bits in mb_communication_info_t struct (IDFGH-9713)](https://github.com/espressif/esp-modbus/issues/25) (Status: released)
 * [Expose option to specify stop bits for ModBus Serial. (IDFGH-6341)](https://github.com/espressif/esp-idf/issues/8003) (Status: released)
 * [add support to change modbus timing characteristics at run time](IDFGH-7007) (Status: released)
 * [Is there any way to suspend and resume esp modbus slave task? (IDFGH-8460)](https://github.com/espressif/esp-idf/issues/9922) (Status: released)

## Plans && Status

* IDFGH-7198: Add extended support for float and other types into object dictionary (Status: released);
* Update Modbus TCP Slave support (Is in progress, testing) (Status: released);
* IDFGH-9653: Add Modbus function 43 (Is planned) (Status: postponed);
* Unit testing of all objects + host testing with linux target (Is in progress);
* Add an option for Modbus Master TCP to include connection phase for each read/write request and close connection after completion of the request. The current implementation starts connection phase to each registered slave when the master object is created (Is planned);
* Fix Modbus IPv6 address support and name resolution in IPv6 networks, delegated modbus segment names + CI testing. (Status: is planned);

Any comments are appreciated.

**Comment by Silvesterrr** [comment]
How are tests at Modbus TCP Slave support going? When is it possible to expect it?

**Reply by alisitsyn** [reply]
@Silvesterrr, 

The testing is still in progress due to other things to do. The TCP feature is scheduled to be completed up to esp-idf v5.4 release.
However, it works and I will try to update the beta release branch as soon as possible and inform about the change accordingly.

Thank you for patience.

**Reply by alisitsyn** [reply]
@Silvesterrr, the [release/v2.0](https://github.com/espressif/esp-modbus/tree/release/v2.0) is updated. The updated version supports the multi-instance TCP Slave and Master with its own communication options. The pre-release esp-modbus component version [2.0.0-beta.1](https://components.espressif.com/components/espressif/esp-modbus/versions/2.0.0-beta.1) can be selected by `idf_component.yml` in main folder like below:

``` yml
dependencies:
  idf:
     version: ">=4.1.0"
  espressif/esp-modbus:
    version: "^2.0.0-beta"
  espressif/mdns:
    version: "^1.0.0"
    rules:
      - if: "idf_version >=5.0"
  mb_example_common:
    path: "../mb_example_common"
  protocol_examples_common:
    path: ${IDF_PATH}/examples/common_components/protocol_examples_common
```
